export const UI_TEXT = {
  // 헤더 및 네비게이션
  APP_TITLE: 'Project Collab',
  APP_SUBTITLE: '팀 프로젝트 & 작업 관리 협업 플랫폼',
  USER_SWITCHER_LABEL: '접속자:',
  BTN_NEW_USER: '+ 새 사용자 등록',
  
  // 사이드바
  MY_PROJECTS_TITLE: '내 프로젝트',
  BTN_NEW_PROJECT: '+ 새 프로젝트 생성',
  NO_PROJECTS: '참여 중인 프로젝트가 없습니다.',
  NO_DESCRIPTION: '설명 없음',
  
  // 작업 대시보드
  ROLE_PREFIX: '내 권한:',
  BTN_NEW_TASK: '+ 새 작업 추가',
  BTN_MANAGE_MEMBERS: (count) => `👥 멤버 관리 (${count})`,
  BTN_MANAGE_LABELS: (count) => `🏷️ 라벨 관리 (${count})`,
  BTN_DELETE_PROJECT: '프로젝트 삭제',
  SEARCH_PLACEHOLDER: '작업 제목 또는 상세 설명 검색...',
  TOTAL_COUNT_PREFIX: '총',
  TOTAL_COUNT_SUFFIX: '건',
  
  // 상태 레이블
  LABEL_ALL: '전체 라벨',
  STATUS_ALL: '전체 상태',
  STATUS_TODO: '할 일 (TODO)',
  STATUS_IN_PROGRESS: '진행 중 (IN_PROGRESS)',
  STATUS_DONE: '완료 (DONE)',
  NO_TASKS: '작업 없음',
  UNASSIGNED: '미배정',
  
  // 카드 툴팁 및 버튼 액션
  TOOLTIP_TASK_DETAIL: '클릭하여 상세/수정',
  TOOLTIP_EDIT_TASK: '작업 상세 및 수정',
  TOOLTIP_DELETE_TASK: '작업 삭제',
  TOOLTIP_EDIT_PROJECT: '프로젝트 정보 수정',
  TOOLTIP_MOVE_TODO: 'TODO로 이동',
  TOOLTIP_MOVE_PROGRESS: '진행중으로 이동',
  TOOLTIP_MOVE_DONE: '완료로 이동',
  TOOLTIP_CLEAR_SEARCH: '검색어 지우기',
  TOOLTIP_CLOSE: '닫기',
  TOOLTIP_DELETE_LABEL: '라벨 삭제',
  
  // 마감일 D-Day 텍스트 포맷터
  DUE_DONE: (date) => `완료 (${date})`,
  DUE_OVERDUE: (days) => `🚨 기한 초과 (${days}일 지남)`,
  DUE_TODAY: '⚡ D-Day (오늘 마감)',
  DUE_NEAR: (days, date) => `⏰ D-${days} (${date})`,
  DUE_NORMAL: (date) => `📅 ${date}`,
  
  // 페이지네이션
  PAGE_PREV: '◀ 이전',
  PAGE_NEXT: '다음 ▶',
  PAGE_INFO: (current, total) => `${current} / ${total} 페이지`,
  PER_PAGE_10: '10개씩',
  PER_PAGE_20: '20개씩',
  PER_PAGE_50: '50개씩',
  
  // 멤버 관리 모달
  MEMBERS_LIST_TITLE: (count) => `참여 멤버 목록 (${count}명)`,
  TH_USER: '사용자',
  TH_ROLE_CHANGE: '역할 변경',
  TH_JOINED_AT: '참여일',
  TH_MANAGE: '관리',
  TOOLTIP_REMOVE_MEMBER: '멤버 제외',
  OPTION_SELECT_USER: '사용자 선택',

  // 라벨 관리 모달
  MODAL_LABELS_TITLE: '프로젝트 라벨 관리',
  LABEL_NAME: '라벨 이름 *',
  PLACEHOLDER_LABEL_NAME: '예: 디자인, 신메뉴, 긴급',
  LABEL_COLOR: '라벨 색상',
  BTN_ADD_LABEL: '+ 라벨 추가',
  LABELS_LIST_TITLE: (count) => `등록된 라벨 목록 (${count}개)`,
  NO_LABELS: '등록된 라벨이 없습니다. 위에서 새 라벨을 추가해보세요!',
  
  // 모달 타이틀 & 폼 레이블
  MODAL_NEW_TASK_TITLE: '신규 작업 등록',
  MODAL_EDIT_TASK_TITLE: '📌 작업 상세 및 수정',
  MODAL_NEW_PROJECT_TITLE: '신규 프로젝트 생성',
  MODAL_EDIT_PROJECT_TITLE: '✏️ 프로젝트 정보 수정',
  MODAL_MEMBERS_TITLE: '프로젝트 멤버 관리 & 초대',
  MODAL_NEW_USER_TITLE: '신규 사용자 등록',
  LABEL_TITLE: '제목 *',
  PLACEHOLDER_TASK_TITLE: '작업 제목을 입력하세요',
  LABEL_USER_NAME: '사용자 이름 *',
  PLACEHOLDER_USER_NAME: '예: 손흥민, 박지성',
  LABEL_PROJECT_NAME: '프로젝트명 *',
  PLACEHOLDER_PROJECT_NAME: '프로젝트 이름을 입력하세요',
  LABEL_DESCRIPTION: '상세 설명',
  PLACEHOLDER_TASK_DESC: '작업 상세 내용',
  PLACEHOLDER_TASK_EDIT_DESC: '작업에 대한 상세 설명...',
  PLACEHOLDER_PROJECT_DESC: '프로젝트에 대한 설명을 입력하세요',
  LABEL_ASSIGNEE: '담당자 지정',
  LABEL_STATUS: '상태 *',
  LABEL_DUE_DATE: '마감일 (Due Date)',
  LABEL_TAGS: '라벨 (Labels)',
  LABEL_USER_SELECT: '사용자 선택 *',
  LABEL_ROLE_SELECT: '역할 부여 *',
  OPTION_UNASSIGNED: '미지정',
  BTN_CANCEL: '취소',
  BTN_CLOSE: '닫기',
  BTN_SUBMIT: '생성하기',
  BTN_SAVE: '저장하기',
  BTN_INVITE: '초대하기',
  
  // 토스트 타이틀
  TITLE_SUCCESS_USER_CREATE: '사용자 등록 완료',
  TITLE_SUCCESS_PROJECT_CREATE: '프로젝트 생성',
  TITLE_SUCCESS_PROJECT_UPDATE: '프로젝트 수정 완료',
  TITLE_SUCCESS_MEMBER_INVITE: '멤버 초대 성공',
  TITLE_SUCCESS_LABEL_CREATE: '라벨 추가 완료',
  TITLE_ERROR_USER_CREATE: '사용자 등록 실패',
  TITLE_ERROR_PROJECT_CREATE: '생성 실패',
  TITLE_ERROR_PROJECT_UPDATE: '수정 실패',
  TITLE_ERROR_TASK_CREATE: '작업 생성 실패',
  TITLE_ERROR_TASK_UPDATE: '작업 수정 실패',
  TITLE_ERROR_MEMBER_INVITE: '초대 실패',
  TITLE_ERROR_MEMBER_ROLE: '역할 변경 실패',
  TITLE_ERROR_MEMBER_REMOVE: '멤버 제외 실패',
  TITLE_ERROR_LABEL_CREATE: '라벨 생성 실패',
  TITLE_ERROR_LABEL_DELETE: '라벨 삭제 실패',
  
  // 피드백 & 에러 메시지
  ERR_NETWORK: '네트워크 오류가 발생했습니다.',
  ERR_USER_CREATE_FAIL: '사용자 등록에 실패했습니다.',
  ERR_TASK_CREATE_FAIL: '작업 생성에 실패했습니다.',
  ERR_TASK_UPDATE_FAIL: '작업 수정 실패: 권한이 없거나 동시 수정 충돌이 발생했습니다.',
  ERR_TASK_DELETE_FAIL: '작업 삭제 실패: 담당자 본인 또는 관리자만 삭제할 수 있습니다.',
  ERR_PROJECT_DELETE_FAIL: '프로젝트 삭제 실패: OWNER만 삭제할 수 있습니다.',
  ERR_PROJECT_UPDATE_FAIL: '프로젝트 수정 실패: OWNER 또는 ADMIN 권한이 필요합니다.',
  ERR_MEMBER_ROLE_FAIL: '역할 변경 실패: 마지막 OWNER는 역할을 변경할 수 없습니다.',
  ERR_MEMBER_REMOVE_FAIL: '멤버 제외 실패: 마지막 OWNER는 프로젝트에서 탈퇴할 수 없습니다.',
  ERR_LABEL_CREATE_FAIL: '라벨 생성 실패: 이름이 중복되었거나 권한이 없습니다.',
  ERR_LABEL_DELETE_FAIL: '라벨 삭제 실패: OWNER 또는 ADMIN 권한이 필요합니다.',
  SUCCESS_USER_CREATE: (name) => `'${name}' 사용자가 등록되었습니다.`,
  SUCCESS_PROJECT_CREATE: (name) => `'${name}' 프로젝트가 생성되었습니다.`,
  SUCCESS_PROJECT_UPDATE: '프로젝트 정보가 수정되었습니다.',
  SUCCESS_TASK_CREATE: '새 작업이 추가되었습니다.',
  SUCCESS_TASK_UPDATE: '작업이 성공적으로 수정되었습니다.',
  SUCCESS_TASK_STATUS_CHANGE: (status) => `작업 상태가 '${status}'(으)로 변경되었습니다.`,
  SUCCESS_TASK_DELETE: '작업이 삭제되었습니다.',
  SUCCESS_PROJECT_DELETE: '프로젝트가 삭제되었습니다.',
  SUCCESS_MEMBER_INVITE: '멤버가 프로젝트에 초대되었습니다.',
  SUCCESS_MEMBER_ROLE: '멤버 역할이 변경되었습니다.',
  SUCCESS_MEMBER_REMOVE: '멤버가 프로젝트에서 제외되었습니다.',
  SUCCESS_LABEL_CREATE: '새 라벨이 추가되었습니다.',
  SUCCESS_LABEL_DELETE: '라벨이 삭제되었습니다.',
  CONFIRM_TASK_DELETE: '정말로 이 작업을 삭제하시겠습니까?',
  CONFIRM_PROJECT_DELETE: '정말로 이 프로젝트를 삭제하시겠습니까? (하위 작업 모두 삭제)',
  CONFIRM_MEMBER_REMOVE: '정말로 이 멤버를 프로젝트에서 제외하시겠습니까?',
  CONFIRM_LABEL_DELETE: '정말로 이 라벨을 삭제하시겠습니까?'
};
